# Generated by Django 5.2 on 2025-06-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineJudge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='memory_limit',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='problem',
            name='time_limit',
            field=models.CharField(max_length=8),
        ),
    ]
