# Generated by Django 5.2 on 2025-07-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineJudge', '0004_alter_problem_difficulty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='problem',
            name='constraints',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='default_code',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='problem',
            name='examples',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='problem',
            name='hints',
            field=models.TextField(blank=True, null=True),
        ),
    ]
